### PR TITLE
3.0.0 beta

### PR DESCRIPTION
**Pull request by kevinhankens**
I'm going to go ahead and open up this to broader review as I believe it is getting very close. Here are some highlights:

- Adheres to the Acquia HMAC 2.0 spec (request and response), validated against the go and ruby libraries
- Has 100% test coverage and tests the behaviors using the shared Acquia HMAC test fixtures
- The PHP API allows for composition, but provides a simple client interface
- Requires PSR-7 messaging and retains Guzzle middleware integration as a first-class citizen
- Provides an easy example of integrating with Symfony apps

Thanks in large part to the hard work of @itafroma and builds on the great foundation already provided by version 2.0 ;)

This is certainly still in a beta state, but is solidifying nicely. It could use some more eyeballs and possibly some revisions and bug testing. However, I think that it is ready to make available to those willing to test it in real-world applications. CI Pipelines will start using this immediately and I believe that N3 is ready to start integrating soon. We should decide on how to proceed. We could keep this effort going in the 3.0.0-beta branch or merge into master.

Please advise :)

### CODE REVIEW

**Comment by pwolanin** [comment]
Making a 3.0 branch for the 2.0 spec seems a bit confusing.   Is there some other way to name it?

**Comment by pwolanin** [comment]
In fact there is not an existing 2.0 branch?  Can you please rename this branch to align with the others?

**Comment by cpliakas** [comment]
@pwolanin There is a 2.0 release, master is effectively tied to that. We had to cut a 2.0 to support Guzzle 6, so it was a major breaking API change.

This definitely trips people up, but I am not sure it is avoidable unless we want to break semantic versioning which I am not in favor of.

**Comment by pwolanin** [comment]
Uh, ok.  That is pretty confusing.

How about 2.2.x?

I realize that breaks semver somewhat, but it seems less confusing than 3.0.x?

This actually echoes the semver debate on Drupal.org where there is essentially unhappiness that Semver doesn't have a way to specify some kind of upstream framework compatibility version

**Comment by cpliakas** [comment]
Yeah, totally sucks. You aren't the first person who has been confused by this either.

I am most concerned about people who have a "http-hmac-php": "~2.0" requirement. If we cut a 2.2, then their stuff will break. I would opt for confusion w/ heavy documentation (maybe with an apology) over no confusion but the potential for breaking people's stuff. Would definitely like to hear other people's thoughts, though, as I could be being a little too conservative on this.

**Comment by cpliakas** [comment]
@scor, thoughts? I know you had similar feedback as @pwolanin.

**Comment by scor** [comment]
Yes, that sucks. For a while you had to install Drush 7 in order to work with Drupal 8, but that was easier to fix.

Do we have any idea if 2.0.0 was downloaded a lot? I wish we could go back in time, but given the situation, 2.2.x would be my preference even if it trips some people.

**Comment by pwolanin** [comment]
Well, I assume most of those people will have a lock file and test before updating?

Does composer even support such loose dependencies?
https://getcomposer.org/doc/02-libraries.md

**Comment by itafroma** [comment]
@pwolanin it does; it's common in the Symfony world to lock on `~n.0` with the assumption that minor versions will only be API additions in accordance with semver.

My preference is to maintain semver and call this 3.0.0: we not only swapped out the spec, but changed the public API. We should be good neighbors in the broader PHP community and try not to violate the principle of least astonishment with our versioning scheme. It's a shame it doesn't line up with the version of the spec, but we'll have to bump the version every time Guzzle releases a new major version, anyway.

**Comment by cpliakas** [comment]
@itafroma Thanks for weighing in.

To @scor's question, I am not sure if we have that level of visibility. Maybe packagist gives us those metrics, but I don't think so.

We do have 6 [dependents](https://packagist.org/packages/acquia/http-hmac-php/dependents), 5 of which are outside of Acquia (i.e. we do not control). Looking through their requirements we would break some of them.

**Comment by mundanity** [comment]
As someone who has been tripped up by the v2 spec vs 3.0 branch, I'm in favour of maintaining semver. Good neighbours and all that. We can doc around existing confusion for sure.

**Comment by kevinhankens** [comment]
I agree that maintaining semver is more important than tripping up a small number of people. I'm going to vote that we go with 3.0.0 and include some very obvious documentation in the readme.

Can we make a decision on this relatively soon so that this doesn't linger? Network and Pipelines both need to start using this right away. It would be nice to use an official version asap :)

Thanks!!

**Comment by scor** [comment]
I'm ok with 3.0.0...

**Comment by cpliakas** [comment]
@kevinhankens @itafroma I say you guys make a call since you did the work to incorporate the V2 spec. You've earned the right to own this decision.

**Comment by kevinhankens** [comment]
Awesome thanks for everyone's comments. We are going to merge now and tag 3.0.0-beta1. Both teams will be integrating and testing this sprint, so once we feel comfortable with the stability, we will tag 3.0.0.

**Comment by itafroma** [comment]
Tagged 3.0.0-beta1: https://github.com/acquia/http-hmac-php/releases/tag/3.0.0-beta1

**Pull request merged**
